repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      # standard end of line/end of file cleanup
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # ensure syntaxes are valid
      - id: check-toml
      - id: check-yaml
      # catch git merge/rebase problems
      - id: check-merge-conflict
      # sort requirements files
      - id: file-contents-sorter
        files: |
          (?x)^(
            .*/requirements\.txt
          )
        args: [--unique]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6fec9b7edb08fd9989088709d864a7826dc74e80  # frozen: v0.15.12
    hooks:
      # lint & attempt to correct failures (e.g. pyupgrade)
      - id: ruff-check
        args: [--fix]
      # compatible replacement for black
      - id: ruff-format
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --trailing-commas]
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 8d1b9cadaf854cb25bb0b0f5870e1cc66a083d6b  # frozen: 0.2.3
    hooks:
      - id: yamlfmt
        # ruamel.yaml doesn't line wrap correctly (?) so set width to 1M to avoid issues
        args: [--mapping=2, --offset=2, --sequence=4, --width=1000000, --implicit_start]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: ed81924a8b1cecdaa570b072528fa80c9c4d6ccd  # frozen: 0.37.1
    hooks:
      # verify github syntaxes
      - id: check-github-actions
        files: .*/action.(yml|yaml)$
      - id: check-github-workflows
      - id: check-dependabot
  - repo: https://github.com/codespell-project/codespell
    # see setup.cfg
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
    hooks:
      - id: codespell
        args: [--write-changes]
  - repo: meta
    # see https://pre-commit.com/#meta-hooks
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
