[tool.codespell]
# see https://github.com/codespell-project/codespell#using-a-config-file
skip = '.git'

[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "FA",  # flake8-future-annotations
  "I",  # isort
  "ISC",  # flake8-implicit-str-concat
  "RUF100",  # Unused noqa directive
  "T10",  # flake8-debugger
  "TCH",  # flake8-type-checking
  "UP",  # pyupgrade
  "W",  # pycodestyle warnings
]
