name: Prepare Release
description: Prepares a release by running towncrier and creating a PR with the changes.
inputs:
  version:
    description: Release version.
    required: true
  branch:
    description: Target branch for the release. Unless specified, uses the default branch.
  token:
    description: >-
      GitHub token to fork repository and create changelog PR
      (`contents: write` and `pull-request: write` for fine-grained PAT; `repo` for classic PAT).
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Checkout Source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Create Branch
      shell: bash
      run: |
        if git fetch origin "${{ inputs.branch }}"; then
          # if branch already exists, checkout and pull
          git checkout "${{ inputs.branch }}"
          git pull origin "${{ inputs.branch }}"
        else
          # if branch doesn't exist, create and push
          git checkout -b "${{ inputs.branch }}"
          git push -u origin "${{ inputs.branch }}"
        fi

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: pip
        cache-dependency-path: news/requirements.txt

    - name: Pip Install
      shell: bash
      run: pip install -r news/requirements.txt

    - name: Pip List
      shell: bash
      run: pip list

    - name: Run Townscrier
      shell: bash
      run: townscrier build --version ${{ inputs.version }}

    # - name: Detect Contributors

    # - name: Detect First-Time Contributors

    - name: Create Fork
      # no-op if the repository is already forked
      shell: bash
      run: echo FORK=$(gh repo fork --clone=false --default-branch-only 2>&1 | awk '{print $1}') >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ inputs.fork_token }}

    - name: Create PR
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        push-to-fork: ${{ env.FORK }}
        token: ${{ inputs.pr_token }}
        branch: changelog-${{ inputs.version }}
        base: ${{ inputs.branch }}
        delete-branch: true
        commit-message: Changelog ${{ inputs.version }}
        author: ${{ inputs.changelog_author }}
        committer: ${{ inputs.changelog_author }}
        title: Changelog ${{ inputs.version }}
        body: |
          [release.yml]: ${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/release.yml

          ✂️ snip snip ✂️ the making of a new release.

          This PR was triggered by @${{ github.triggering_actor }} via ${{ github.event_name }}.

          ###### Auto-generated by the [`release.yml`][release.yml] workflow, see ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
