name: Combine Durations
description: Combine the duration files from recent pytest runs.
author: Anaconda Inc.
branding:
  icon: book-open
  color: green

inputs:
  branch:
    description: The branch to search for recent pytest runs.
    default: main
  durations-dir:
    description: The directory to write the combined durations file.
    default: durations
  pattern:
    description: The pattern to search for recent pytest runs.
    default: '*-all'
  token:
    description: >-
      A token with ability to comment, label, and modify the commit status
      (`pull_request: write` and `statuses: write` for fine-grained PAT; `repo` for classic PAT)
    default: ${{ github.token }}
  workflow:
    description: The workflow to search for recent pytest runs.
    default: tests.yml
  repository:
    description: The repository to search for recent pytest runs.
    default: ${{ github.repository }}
outputs:
  summary:
    description: Summary of the durations that were combined.
    value: ${{ steps.combine.outputs.summary }}

runs:
  using: composite
  steps:
    - name: Download Recent Artifacts
      shell: bash
      run: >
        gh run list
        --repo ${{ inputs.repository }}
        --branch ${{ inputs.branch }}
        --workflow ${{ inputs.workflow }}
        --limit 10
        --json databaseId
        --jq '.[].databaseId'
        | xargs -n 1
        gh run download
        --repo ${{ inputs.repository }}
        --dir ${{ runner.temp }}/artifacts/
        --pattern '${{ inputs.pattern }}'
        || true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.cache/pip
        # invalidate the cache anytime a workflow changes
        key: ${{ hashFiles('.github/workflows/*') }}

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.11'

    - name: Install Dependencies
      shell: bash
      run: pip install --quiet -r ${{ github.action_path }}/requirements.txt

    - name: Pip List
      shell: bash
      run: |
        echo ::group::Pip List
        pip list
        echo ::endgroup::

    - name: Combine Recent Durations
      id: combine
      shell: bash
      run: >
        python ${{ github.action_path }}/action.py
        --durations-dir=${{ inputs.durations-dir }}
        --artifacts-dir=${{ runner.temp }}/artifacts/
