name: Combine Durations
description: Combine the duration files from recent pytest runs.
author: Anaconda Inc.
branding:
  icon: book-open
  color: green

inputs:
  branch:
    description: The branch to search for recent pytest runs.
    default: main
  durations-dir:
    description: The directory to write the combined durations file.
    default: durations
  pattern:
    description: The pattern to search for recent pytest runs.
    default: '*-all'
  token:
    description: >-
      A token with ability to comment, label, and modify the commit status
      (`pull_request: write` and `statuses: write` for fine-grained PAT; `repo` for classic PAT)
    default: ${{ github.token }}
  workflow:
    description: The workflow to search for recent pytest runs.
    default: tests.yml
  repository:
    description: The repository to search for recent pytest runs.
    default: ${{ github.repository }}
outputs:
  summary:
    description: Summary of the durations that were combined.
    value: ${{ steps.combine.outputs.summary }}

runs:
  using: composite
  steps:
    - name: Download Recent Artifacts
      shell: bash
      run: >
        gh run list
        --repo ${{ inputs.repository }}
        --branch ${{ inputs.branch }}
        --workflow ${{ inputs.workflow }}
        --limit 10
        --json databaseId
        --jq '.[].databaseId'
        | xargs -n 1
        gh run download
        --repo ${{ inputs.repository }}
        --dir ${{ runner.temp }}/artifacts/
        --pattern '${{ inputs.pattern }}'
        || true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # `hashFiles` only works on files within the working directory, since `requirements.txt`
    # is not in the working directory we need to manually compute the SHA256 hash
    - name: Compute Hash
      id: hash
      shell: bash
      run: echo hash=$(sha256sum ${{ github.action_path }}/requirements.txt | awk '{print $1}') >> $GITHUB_OUTPUT

    - name: Pip Cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: ~/.cache/pip
        key: ${{ github.workflow }}-combine-durations-${{ steps.hash.outputs.hash }}

    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '>=3.9'

    - name: Pip Install
      shell: bash
      run: pip install --quiet -r ${{ github.action_path }}/requirements.txt

    - name: Pip List
      shell: bash
      run: pip list

    - name: Combine Recent Durations
      id: combine
      shell: bash
      run: >
        python ${{ github.action_path }}/combine_durations.py
        --durations-dir=${{ inputs.durations-dir }}
        --artifacts-dir=${{ runner.temp }}/artifacts/
