name: Read File
description: Read a local file or remote URL.
author: Anaconda Inc.
branding:
  icon: book-open
  color: green

inputs:
  path:
    description: Local path or remote URL to the file to read.
    required: true
  parser:
    description: Parser to use for the file. Choose json, yaml, or null (to leave it as plain text).
  default:
    description: File contents to use if the file is not found.
outputs:
  content:
    description: File contents as a JSON object (if a parser is specified) or the raw text.
    value: ${{ steps.read.outputs.content }}

runs:
  using: composite
  steps:
    # `hashFiles` only works on files within the working directory, since `requirements.txt`
    # is not in the working directory we need to manually compute the SHA256 hash
    - name: Compute Hash
      id: hash
      shell: bash
      run: echo hash=$(sha256sum ${{ github.action_path }}/requirements.txt | awk '{print $1}') >> $GITHUB_OUTPUT

    - name: Pip Cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: ~/.cache/pip
        key: ${{ github.workflow }}-read-file-${{ steps.hash.outputs.hash }}

    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '>=3.10'

    - name: Pip Install
      shell: bash
      run: pip install --quiet -r ${{ github.action_path }}/requirements.txt

    - name: Pip List
      shell: bash
      run: pip list

    - name: Read JSON
      id: read
      shell: bash
      run: >
        python ${{ github.action_path }}/read_file.py
        "${INPUT_PATH}"
        ${INPUT_PARSER:+"--parser=${INPUT_PARSER}"}
        ${INPUT_DEFAULT:+"--default=${INPUT_DEFAULT}"}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_PARSER: ${{ inputs.parser }}
        INPUT_DEFAULT: ${{ inputs.default }}
