name: Create Fork
description: Creates a fork of the current repository.
inputs:
  token:
    description: |
      GitHub token to create fork of current repository.
      Fine-grained PAT: `administration: write`
    default: ${{ github.token }}
  timeout:
    description: Seconds to wait after creating forked repository.
    default: '60'
outputs:
  fork:
    description: The full name of the fork created, e.g., owner/repo.
    value: ${{ steps.create_fork.outputs.fork }}
runs:
  using: composite
  steps:
    - name: Create Fork
      id: create_fork
      # no-op if the repository is already forked
      shell: bash
      # don't use `gh repo fork` since it doesn't provide consistent output
      # see: https://github.com/cli/cli/issues/10079
      run: |
        # create the fork
        RESPONSE=$(gh api \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          "/repos/${{ github.repository }}/forks" \
          -f default_branch_only=true)

        # extract values with jq
        FULL_NAME="$(echo "${RESPONSE}" | jq -r '.full_name')"
        CREATED_AT="$(echo "${RESPONSE}" | jq -r '.created_at')"

        # wait a minute to ensure the fork is ready
        TIMESTAMP="$(date -d "${CREATED_AT}" +%s)"
        CURRENT="$(date +%s)"
        [ $((CURRENT - TIMESTAMP)) -gt 60 ] || sleep ${{ inputs.timeout }}

        # store values for subsequent usage
        echo fork="${FULL_NAME}" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.token }}
