name: Template Files
description: Template (or copy) files from other repositories and commits them to the specified PR.
author: Anaconda Inc.
branding:
  icon: book-open
  color: green

inputs:
  config:
    description: Configuration path defining what files to template/copy.
    default: .github/template-files/config.yml
  stubs:
    description: >-
      Path to where stub files are located in the current repository.
    default: .github/template-files/templates/
  token:
    description: >-
      A token with ability to comment, label, and modify the commit status
      (`pull_request: write` and `statuses: write` for fine-grained PAT; `repo` for classic PAT)
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.cache/pip
        # invalidate the cache anytime a workflow changes
        key: ${{ hashFiles('.github/workflows/*') }}

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.11'

    - name: install dependencies
      shell: bash
      run: pip install --quiet -r ${{ github.action_path }}/requirements.txt

    - name: sync & template files
      shell: bash
      run: python ${{ github.action_path }}/action.py --config ${{ inputs.config }} --stubs ${{ inputs.stubs }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
