name: CLA check
description: Reacts to new PRs and check if the contributor has previously signed the conda contributor license agreement (CLA).
inputs:
  token:
    description: >-
      A token with ability to comment, label, and modify the commit status
      (`pull_request: write` and `statuses: write` for fine-grained PAT; `repo` for classic PAT)
    default: ${{ github.token }}
    required: true
  label:
    description: Label to apply to contributor's PR once CLA is signed
    required: true
  cla_repo:
    description: Upstream repository in which to create PR
    default: conda/infrastructure
  cla_path:
    description: Path to the CLA signees file within the provided `cla_repo`
    default: .clabot
  cla_fork:
    description: Fork of `cla_repo` in which to create branch
    default: conda-bot/infrastructure
  cla_token:
    description: >-
      Token for opening signee PR in `cla_fork`
      (`pull_request: write` for fine-grained PAT; `repo` and `workflow` for classic PAT)
    required: true
  cla_author:
    description: Git-format author/committer to use for pull request commits
    default: Conda Bot <18747875+conda-bot@users.noreply.github.com>
  # Optional inputs for workflow_run trigger (when context.issue is not available)
  pr_number:
    description: PR number (optional, for workflow_run triggers)
    required: false
  pr_author:
    description: PR author username (optional, for workflow_run triggers)
    required: false
  pr_url:
    description: PR URL (optional, for workflow_run triggers)
    required: false
  pr_sha:
    description: PR head SHA (optional, for workflow_run triggers)
    required: false

runs:
  using: composite
  steps:
    # if triggered by a comment, leave a reaction
    - name: React to comment
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
      if: github.event_name == 'issue_comment'
      with:
        token: ${{ inputs.token }}
        comment-id: ${{ github.event.comment.id }}
        reactions: eyes

    # commit status → pending
    - name: Set commit status with pending
      uses: conda/actions/set-commit-status@f05161c6e6e37a49b17c8e0b436197b53830318a # v25.9.2
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: Checking conda CLA...
        state: pending

    # has_label, number, contributor, url, has_signed
    - name: Collect PR metadata
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      id: metadata
      env:
        INPUT_LABEL: ${{ inputs.label }}
        INPUT_CLA_REPO: ${{ inputs.cla_repo }}
        INPUT_CLA_PATH: ${{ inputs.cla_path }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}
        INPUT_PR_AUTHOR: ${{ inputs.pr_author }}
        INPUT_PR_URL: ${{ inputs.pr_url }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const { owner, repo } = context.repo;

          // Use provided inputs or fall back to context
          const number = process.env.INPUT_PR_NUMBER
            ? parseInt(process.env.INPUT_PR_NUMBER, 10)
            : context.issue.number;

          core.debug(`owner: ${owner}`);
          core.debug(`repo: ${repo}`);
          core.setOutput('number', number);
          core.debug(`number: ${number}`);

          const raw = await github.rest.pulls.get({
            owner: owner,
            repo: repo,
            pull_number: number
          });
          const labels = raw.data.labels.map(label => label.name);
          core.debug(`labels: ${labels}`);

          const has_label = labels.includes(process.env.INPUT_LABEL);
          core.setOutput('has_label', has_label);
          core.debug(`has_label: ${has_label}`);

          const cla_repo = process.env.INPUT_CLA_REPO.split('/', 2);
          const { content, encoding } = (await github.rest.repos.getContent({
            owner: cla_repo[0],
            repo: cla_repo[1],
            path: process.env.INPUT_CLA_PATH
          })).data;
          const contributors = JSON.parse(
            Buffer.from(content, encoding).toString('utf-8')
          ).contributors;
          core.debug(`contributors: ${contributors}`);

          // Use provided author or get from PR data
          const contributor = process.env.INPUT_PR_AUTHOR || raw.data.user.login;
          core.setOutput('contributor', contributor);
          core.debug(`contributor: ${contributor}`);

          // Use provided URL or get from PR data
          const url = process.env.INPUT_PR_URL || raw.data.html_url;
          core.setOutput('url', url);
          core.debug(`url: ${url}`);

          const has_signed = contributors.includes(contributor);
          core.setOutput('has_signed', has_signed);
          core.debug(`has_signed: ${has_signed}`);

    # if contributor has already signed, add [cla-signed] label
    - name: Add label to PR
      uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf
      if: steps.metadata.outputs.has_signed == 'true' && steps.metadata.outputs.has_label == 'false'
      with:
        github_token: ${{ inputs.token }}
        labels: ${{ inputs.label }}

    # if contributor has not signed yet, remove [cla-signed] label
    - name: Remove label to PR
      uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
      if: steps.metadata.outputs.has_signed == 'false' && steps.metadata.outputs.has_label == 'true'
      with:
        github_token: ${{ inputs.token }}
        labels: ${{ inputs.label }}

    # if unsigned, checkout cla_repo
    - name: Clone CLA signee repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      if: steps.metadata.outputs.has_signed == 'false'
      with:
        repository: ${{ inputs.cla_repo }}
        persist-credentials: false

    # if unsigned, update cla_path
    - name: Add contributor as a CLA signee
      shell: python
      if: steps.metadata.outputs.has_signed == 'false'
      env:
        INPUT_CLA_PATH: ${{ inputs.cla_path }}
        CONTRIBUTOR: ${{ steps.metadata.outputs.contributor }}
      run: |
        import json
        import os
        from pathlib import Path

        path = Path(os.environ["INPUT_CLA_PATH"])
        signees = json.loads(path.read_text())
        signees["contributors"].append(os.environ["CONTRIBUTOR"])
        signees["contributors"].sort(key=str.lower)
        path.write_text(json.dumps(signees, indent=2) + "\n")

    # if unsigned, create PR
    - name: Create PR with new CLA signee
      uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
      id: pull
      if: steps.metadata.outputs.has_signed == 'false'
      with:
        push-to-fork: ${{ inputs.cla_fork }}
        token: ${{ inputs.cla_token }}
        branch: cla-${{ steps.metadata.outputs.contributor }}
        delete-branch: true
        commit-message: Adding CLA signee ${{ steps.metadata.outputs.contributor }}
        author: ${{ inputs.cla_author }}
        committer: ${{ inputs.cla_author }}
        title: Adding CLA signee ${{ steps.metadata.outputs.contributor }}
        body: |
          Adding CLA signee @${{ steps.metadata.outputs.contributor }}

          Xref ${{ steps.metadata.outputs.url }}

    # if unsigned, create sticky comment
    - name: Create comment regarding missing CLA signature
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
      if: steps.metadata.outputs.has_signed == 'false'
      with:
        number: ${{ steps.metadata.outputs.number }}
        # GitHub flavored markdown reinvents how paragraphs work, adjoined lines of text are not
        # concatenated so instead we rely on YAML multi-line + extra newlines
        message: >-
          [cla]: https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement


          We require contributors to sign our [Contributor License Agreement][cla] and we don't
          have one on file for @${{ steps.metadata.outputs.contributor }}.


          In order for us to review and merge your code, please e-sign the
          [Contributor License Agreement PDF][cla]. We then need to manually verify your
          signature, merge the PR (${{ steps.pull.outputs.pull-request-url }}), and ping the bot
          to refresh the PR.
        GITHUB_TOKEN: ${{ inputs.token }}

    # commit status → error
    - name: Set commit status to error
      if: steps.metadata.outputs.has_signed == 'false'
      uses: conda/actions/set-commit-status@f05161c6e6e37a49b17c8e0b436197b53830318a # v25.9.2
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: Please follow the details link to sign the conda CLA. →
        state: error
        target_url: https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement

    # commit status → success
    - name: Set commit status to success
      if: steps.metadata.outputs.has_signed == 'true'
      uses: conda/actions/set-commit-status@f05161c6e6e37a49b17c8e0b436197b53830318a # v25.9.2
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: CLA signed, thank you!
        state: success
