name: CLA check
description: Reacts to new PRs and check if the contributor has previously signed the conda contributor license agreement (CLA).
inputs:
  token:
    description: >-
      A token with ability to comment, label, and modify the commit status
      (`pull_request: write` and `statuses: write` for fine-grained PAT; `repo` for classic PAT)
    default: ${{ github.token }}
    required: true
  label:
    description: Label to apply to contributor's PR once CLA is signed
    required: true
  cla_repo:
    description: Upstream repository in which to create PR
    default: conda/cla
  cla_path:
    description: Path to the CLA signees file within the provided `cla_repo`
    default: .cla-signers
  cla_token:
    description: >-
      Token for opening signee PR in `cla_fork`
      (`pull_request: write` for fine-grained PAT; `repo` and `workflow` for classic PAT)
    required: true

runs:
  using: composite
  steps:
    # if triggered by a comment, leave a reaction
    - name: React to comment
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      if: github.event_name == 'issue_comment'
      with:
        token: ${{ inputs.token }}
        comment-id: ${{ github.event.comment.id }}
        reactions: eyes

    # commit status → pending
    - name: Set commit status with pending
      uses: conda/actions/set-commit-status@15f883f14f4232f83658e3609c3316d58905138f # v24.8.0
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: Checking conda CLA...
        state: pending

    - name: Determine whether this PR has the label
      run: echo HAS_LABEL=$(${{ contains(github.event.pull_request.labels || github.event.issue.labels, inputs.label) }}) >> $GITHUB_ENV
      shell: bash

    - name: Determine the contributor
      run: echo CONTRIBUTOR=${{ github.event.pull_request.user.login || github.event.issue.user.login }} >> $GITHUB_ENV
      shell: bash

    - name: Read CLA signees
      uses: conda/actions/read-file@read-file
      id: read_cla
      with:
        path: https://raw.githubusercontent.com/${{ inputs.cla_repo }}/main/${{ inputs.cla_path }}
        parser: json
        default: '[]'

    - name: Determine whether the contributor has signed the CLA
      run: echo HAS_SIGNED=${{ contains(fromJSON(steps.read_cla.outputs.content), env.CONTRIBUTOR) }} >> $GITHUB_ENV
      shell: bash

    # if contributor has already signed, add [cla-signed] label
    - name: Add label to PR
      uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3
      if: env.HAS_SIGNED == 'true' && env.HAS_LABEL == 'false'
      with:
        github_token: ${{ inputs.token }}
        labels: ${{ inputs.label }}

    # if contributor has not signed yet, remove [cla-signed] label
    - name: Remove label to PR
      uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
      if: env.HAS_SIGNED == 'false' && env.HAS_LABEL == 'true'
      with:
        github_token: ${{ inputs.token }}
        labels: ${{ inputs.label }}

    # if unsigned, checkout cla_repo
    - name: Clone CLA signee repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      if: env.HAS_SIGNED == 'false'
      with:
        repository: ${{ inputs.cla_repo }}

    - name: Create fork
      if: env.HAS_SIGNED == 'false'
      # no-op if the repository is already forked
      run: echo FORK=$(gh repo fork --clone=false --default-branch-only 2>&1 | awk '{print $1}') >> $GITHUB_ENV
      env:
        GH_TOKEN: ${{ inputs.cla_token }}
      shell: bash

    - name: Setup Python 3.12
      if: env.HAS_SIGNED == 'false'
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.12'

    - name: Add contributor as a CLA signee
      if: env.HAS_SIGNED == 'false'
      shell: bash
      run: python ${{ github.action_path }}/action.py ${{ inputs.cla_path }} ${{ env.CONTRIBUTOR }}

    # if unsigned, create PR
    - name: Create PR with new CLA signee
      uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7.0.1
      id: pull
      if: env.HAS_SIGNED == 'false'
      with:
        push-to-fork: ${{ env.FORK }}
        token: ${{ inputs.cla_token }}
        branch: cla-${{ env.CONTRIBUTOR }}
        delete-branch: true
        commit-message: 🤖 Add ${{ env.CONTRIBUTOR }} as CLA signee
        author: Conda Bot <18747875+conda-bot@users.noreply.github.com>
        committer: Conda Bot <18747875+conda-bot@users.noreply.github.com>
        title: 🤖 Add ${{ env.CONTRIBUTOR }} as CLA signee
        body: Xref ${{ github.event.html_url }}

    # if unsigned, create sticky comment
    - name: Create comment regarding missing CLA signature
      uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
      if: env.HAS_SIGNED == 'false'
      with:
        number: ${{ github.event.number || github.event.issue.number }}
        # GitHub flavored markdown reinvents how paragraphs work, adjoined lines of text are not
        # concatenated so instead we rely on YAML multi-line + extra newlines
        message: >-
          [cla]: https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement


          > [!NOTE]
          > You may have previously signed the conda CLA. That signature is still valid
          > for any prior contributions however conda is now a NumFOCUS project and hence
          > requires new CLAs to be signed for any new contributions.


          We require contributors to sign our [Contributor License Agreement][cla] and we don't
          have one on file for @${{ env.CONTRIBUTOR }}.


          In order for us to review and merge your code, please e-sign the
          [Contributor License Agreement PDF][cla]. We then need to manually verify your
          signature, merge the PR (${{ steps.pull.outputs.pull-request-url }}), and ping the bot
          to refresh the PR.
        GITHUB_TOKEN: ${{ inputs.token }}

    # commit status → error
    - name: Set commit status to error
      if: env.HAS_SIGNED == 'false'
      uses: conda/actions/set-commit-status@15f883f14f4232f83658e3609c3316d58905138f # v24.8.0
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: Please follow the details link to sign the conda CLA. →
        state: error
        target_url: https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement

    # commit status → success
    - name: Set commit status to success
      if: env.HAS_SIGNED == 'true'
      uses: conda/actions/set-commit-status@15f883f14f4232f83658e3609c3316d58905138f # v24.8.0
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: CLA signed, thank you!
        state: success
