name: Check CLA
description: Reacts to new PRs and check if the contributor has previously signed the conda contributor license agreement (CLA).
inputs:
  label:
    description: Label to apply to contributor's PR once the CLA is signed.
    default: cla-signed
  repository:
    description: Repository in which to create PR adding CLA signature.
    default: conda/cla
  path:
    description: Path to the CLA signees file within the provided `repository`.
    default: .cla-signers
  token:
    description: >-
      GitHub token to comment on PRs, change PR labels, modify the commit status, and create pull request.
      Fine-grained PAT: `pull_request: write; statuses: write`
    default: ${{ github.token }}
  fork-token:
    description: |
      GitHub token to create and push to the fork.
      Fine-grained PAT: `administration: write; contents: write`

runs:
  using: composite
  steps:
    - name: Set Comment Reaction [eyes]
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      if: github.event_name == 'issue_comment'
      with:
        token: ${{ inputs.token }}
        comment-id: ${{ github.event.comment.id }}
        reactions: eyes
        reactions-edit-mode: replace

    - name: Set Commit Status [pending]
      uses: conda/actions/set-commit-status@6e72e0db87e72f0020e493aeb02f864363bd9258 # v24.11.1
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: Checking conda CLA...
        state: pending

    - name: Detect PR Label
      id: detect-label
      shell: bash
      run: echo labeled=$(${{ contains(github.event.pull_request.labels || github.event.issue.labels, inputs.label) }}) >> $GITHUB_OUTPUT

    - name: Detect Contributor
      id: detect-contributor
      shell: bash
      run: |
        echo id=${{ github.event.pull_request.user.id || github.event.issue.user.id }} >> $GITHUB_OUTPUT
        echo login=${{ github.event.pull_request.user.login || github.event.issue.user.login }} >> $GITHUB_OUTPUT

    - name: Read CLA Signees
      id: read-cla
      uses: conda/actions/read-file@read-file
      with:
        path: https://raw.githubusercontent.com/${{ inputs.repository }}/main/${{ inputs.path }}
        parser: json
        default: '{}'

    - name: Detect Signature
      id: detect-signature
      shell: bash
      run: echo signed=${{ contains(fromJSON(steps.read-cla.outputs.content), steps.detect-contributor.outputs.id) }} >> $GITHUB_OUTPUT

    - name: Set PR Label
      uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3
      if: steps.detect-signature.outputs.signed == 'true' && steps.detect-label.outputs.labeled == 'false'
      with:
        github_token: ${{ inputs.token }}
        labels: ${{ inputs.label }}

    - name: Remove PR Label
      uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
      if: steps.detect-signature.outputs.signed == 'false' && steps.detect-label.outputs.labeled == 'true'
      with:
        github_token: ${{ inputs.token }}
        labels: ${{ inputs.label }}

    - name: Clone CLA Repository
      if: steps.detect-signature.outputs.signed == 'false'
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.repository }}

    - name: Create Fork
      id: create-fork
      if: steps.detect-signature.outputs.signed == 'false'
      uses: conda/actions/create-fork@create-fork
      with:
        token: ${{ inputs.fork-token || inputs.token }}

    - name: Setup Python
      if: steps.detect-signature.outputs.signed == 'false'
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.12'

    - name: Add Contributor Signature
      if: steps.detect-signature.outputs.signed == 'false'
      shell: bash
      run: >
        python ${{ github.action_path }}/action.py
        ${{ inputs.path }}
        --id=${{ steps.detect-contributor.outputs.id }}
        --login=${{ steps.detect-contributor.outputs.login }}

    - name: Create PR
      id: pull
      if: steps.detect-signature.outputs.signed == 'false'
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        # push to the fork
        branch-token: ${{ inputs.fork-token || inputs.token }}
        push-to-fork: ${{ steps.create-fork.outputs.fork }}
        branch: cla-${{ steps.detect-contributor.outputs.id }}
        commit-message: 🤖 Add ${{ steps.detect-contributor.outputs.login }} (${{ steps.detect-contributor.outputs.id }}) as CLA signee
        author: Conda Bot <18747875+conda-bot@users.noreply.github.com>
        committer: Conda Bot <18747875+conda-bot@users.noreply.github.com>
        # create PR
        token: ${{ inputs.fork-token }}
        delete-branch: true
        title: 🤖 Add ${{ steps.detect-contributor.outputs.login }} (${{ steps.detect-contributor.outputs.id }}) as CLA signee
        body: Xref ${{ github.event.pull_request.user.html_url || github.event.issue.user.html_url }}

    - name: Create Comment
      uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2.9.0
      if: steps.detect-signature.outputs.signed == 'false'
      with:
        number: ${{ github.event.number || github.event.issue.number }}
        # GitHub flavored markdown reinvents how paragraphs work, adjoined lines of text are not
        # concatenated so instead we rely on YAML multi-line + extra newlines
        message: >-
          [cla]: https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement


          > [!NOTE]

          > You may have previously signed the conda CLA. That signature is still valid
          for any prior contributions however conda is now a fiscally sponsored project
          by NumFOCUS and hence requires new CLAs to be signed for any new contributions.


          We require contributors to sign our [Contributor License Agreement][cla] and we don't
          have one on file for @${{ steps.detect-contributor.outputs.login }} (${{ steps.detect-contributor.outputs.id }}).


          In order for us to review and merge your code, please e-sign the
          [Contributor License Agreement PDF][cla]. We then need to manually verify your
          signature, merge the PR (${{ steps.pull.outputs.pull-request-url }}), and ping the bot
          to refresh the PR.


          <details>

          <summary>Commands</summary>


          Trigger actions by commenting on this PR:


          - `@conda-bot check` will check whether a CLA has been signed for this PR author


          </details>
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Set Commit Status [success]
      if: steps.detect-signature.outputs.signed == 'true'
      uses: conda/actions/set-commit-status@6e72e0db87e72f0020e493aeb02f864363bd9258 # v24.11.1
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: CLA signed, thank you!
        state: success

    - name: Set Commit Status [error]
      if: steps.detect-signature.outputs.signed == 'false'
      uses: conda/actions/set-commit-status@6e72e0db87e72f0020e493aeb02f864363bd9258 # v24.11.1
      with:
        token: ${{ inputs.token }}
        context: CLA check
        description: Please follow the details link to sign the conda CLA. →
        target_url: https://conda.io/en/latest/contributing.html#conda-contributor-license-agreement
        state: error

    - name: Set Comment Reaction [hooray/confused]
      uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
      if: github.event_name == 'issue_comment'
      with:
        token: ${{ inputs.token }}
        comment-id: ${{ github.event.comment.id }}
        reactions: ${{ steps.detect-signature.outputs.signed == 'true' && 'hooray' || 'confused' }}
        reactions-edit-mode: replace
