name: 'Canary releases'
description: 'This builds and uploads canary releases of conda to the provided channel and label on anaconda.org.'
inputs:
  pr:
    description: 'Pull request ID'
    required: true
  package-name:
    description: 'Name of package on anaconda.org, needs to match build file name.'
    required: true
  subdir:
    description: 'Subdirectory'
    required: true
  comment-author:
    description: 'Author for build comment'
    required: false
  comment-headline:
    description: 'Headline for build comment'
    required: false
    default: 'Canary release status'
  comment-token:
    description: 'Token for commenting build'
    required: false
  anaconda-org-channel:
    description: 'Channel on anaconda.org'
    required: true
  anaconda-org-label:
    description: 'Label to use on anaconda.org'
    required: true
  anaconda-org-token:
    description: 'Upload token for anaconda.org'
    required: true
runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v2

    - name: Set output variables
      id: vars
      shell: bash -l {0}
      run: |
        echo ::set-output name=run-url::"https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo ::set-output name=status-header::"Status updates for builds"

    - name: Find Comment with status
      uses: peter-evans/find-comment@v1
      if: inputs.comment-token != ''
      id: before-build
      with:
        issue-number: ${{ inputs.pr }}
        comment-author: "${{ inputs.comment-author }}"
        body-includes: "${{ steps.vars.outputs.status-header }}"
        direction: last

    - name: Create comment if there is no status update
      uses: peter-evans/create-or-update-comment@v1
      if: |
        inputs.comment-token != '' &&
        steps.before-build.outputs.comment-id == ''
      with:
        issue-number: ${{ inputs.pr }}
        body: |
          # ${{ inputs.comment-headline }}
          > The workflow for building and uploading a canary release for ${{ inputs.package-name }} with the label `${{ inputs.anaconda-org-label }}` in channel `${{ inputs.anaconda-org-channel }}` [was started](${{ steps.vars.outputs.run-url }}) in #${{ inputs.pr }} by @${{ github.actor }}!

          Once it's done, use this command to try it out in a new conda environment:

          ```
          conda install -c ${{ inputs.anaconda-org-channel }}/label/${{ inputs.anaconda-org-label }} ${{ inputs.package-name }}
          ```

          ------
          ### ${{ steps.vars.outputs.status-header }}
          | Run | Outcome | User | Matrix |
          |---|---|---|---|
        reactions: 'rocket'
        token: ${{ inputs.comment-token }}

    - name: Build & upload package
      # make sure we don't run on forks
      if: github.repository_owner == 'conda'
      id: build
      shell: bash -l {0}
      run: |
        echo "::group::Setting up environment"
        set -euo pipefail
        conda activate
        conda update --yes --quiet conda
        conda install --yes --quiet conda-build anaconda-client git
        echo "::endgroup::"

        echo "::group::Debugging information"
        conda info
        conda config --show-sources
        conda list
        echo "::endgroup::"

        echo "::group::Building package"
        conda build --croot=./pkgs conda.recipe
        echo "::endgroup::"

        echo "::group::Uploading package"
        anaconda --token ${{ inputs.anaconda-org-token }} upload \
          --force --register --no-progress \
          --user ${{ inputs.anaconda-org-channel }} \
          --label ${{ inputs.anaconda-org-label }} \
          ./pkgs/${{ inputs.subdir }}/${{ inputs.package-name }}-*.tar.bz2
        echo "Uploaded the following files:"
        ls ./pkgs/${{ inputs.subdir }}/${{ inputs.package-name }}-*.tar.bz2 | cut -d/ -f3- | tr ' ' $'\n'
        echo "::endgroup::"

        echo "Use this command to try out the build:"
        echo "conda install -c ${{ inputs.anaconda-org-channel }}/label/${{ inputs.anaconda-org-label }} ${{ inputs.package-name }}"

    - name: Find Comment after build
      uses: peter-evans/find-comment@v1
      if: inputs.comment-token != ''
      id: after-build
      with:
        issue-number: ${{ inputs.pr }}
        comment-author: "${{ inputs.comment-author }}"
        body-includes: "${{ steps.vars.outputs.status-header }}"

    - name: Leave comment after build
      if: |
        steps.after-build.output.comment-id != '' &&
        inputs.comment-token != ''
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ inputs.pr }}
        comment-id: ${{ steps.after-build.output.comment-id }}
        body: |
          | [${{ github.run_id }}](${{ steps.vars.outputs.run-url }}) | ${{ steps.build.outcome }} | @${{ github.actor }} | ${{ matrix }} |
        reactions: 'eyes'
        token: ${{ inputs.comment-token }}
