name: Fork context

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

  schedule:
    # https://crontab.guru/#45_*_*_*_*
    - cron: 45 * * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Write GitHub context to log
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
